version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      IS_LOCAL: ${IS_LOCAL}
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
