# BUILDER STAGE
FROM python:3.11-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# RUNTIME STAGE
from python:3.11-slim as runtime
WORKDIR /app
COPY --from=builder
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]