"""Add last_synced_at field

Revision ID: 208c9f261dbd
Revises: dfd61d8dd209
Create Date: 2026-03-28 18:33:37.240119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208c9f261dbd'
down_revision: Union[str, None] = 'dfd61d8dd209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'last_synced_at')
    # ### end Alembic commands ###
